version: "3.8"

services:
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - ./ukb-app-api:/var/www/html
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/logs/nginx:/var/log/nginx
    ports:
      - 80:80
    depends_on: 
      - mysql
      - php-fpm
 
  php-fpm:
    build:
      context: .
      dockerfile: ./php-fpm/Dockerfile
    volumes:
      - ./ukb-app-api:/var/www/html
 
  mysql:
    image: mysql:8.0
    container_name: mysql80
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ukb-app
      MYSQL_ROOT_PASSWORD: root
 
  workspace:
    build:
      context: .
      dockerfile: ./workspace/Dockerfile
    volumes:
      - ./ukb-app-api:/var/www/html
    working_dir: /var/www/html
    tty: true
 